### ISSUE TITLE
Issue with DLL on MacOS

### ISSUE THREAD

**Issue by krstns** [khindemit/unity-rlottie#6]
Hi,

when running the sample on macos, Unity 2020.3.41 I keep getting:
```
DllNotFoundException: LottiePlugin
LottiePlugin.NativeBridge.LoadFromData (System.String filePath, System.String resourcesPath, System.IntPtr& animationWrapper) (at Assets/LottiePlugin/src/NativeBridge.cs:92)
```

It works just fine on windows.

On macos, I had to modify the dependencies and switch:

`    "com.unity.toolchain.linux-x86_64": "1.0.0",`
to

`    "com.unity.toolchain.macos-x86_64-linux-x86_64": "1.0.0",`

Is there anything I am missing?

I didn't give enough details:
Platform: Android
Editor OS: macos

**Comment by khindemit** [comment]
Hello!
Thanks for the report. I rebuilt the dlls and now it works. Please try to pull and try again.

**Comment by krstns** [comment]
Hi @khindemit Thanks for a quick response. I've tried pulling and testing on both 2020.3.44 and 2021.1.9 and it didn't work.
I still get the:
```
DllNotFoundException: LottiePlugin
LottiePlugin.NativeBridge.LoadFromData (System.String filePath, System.String resourcesPath, System.IntPtr& animationWrapper) (at Assets/LottiePlugin/src/NativeBridge.cs:92)
```

and some errors from collab-proxy, but this could be something on my end.
I've cleaned the repo an pulled it again but it changed nothing.

**Comment by khindemit** [comment]
Hello @krstns, this is strange. I tested the Unity 2019.4.40f1 on Mac OSX switched to Standalone and later to iOS.
I also tested the iOS build on iPhone, it works good.
I'll try to test the project in Unity 2020.3.41f1 switched to Android and see if it works for me. I'll keep you updated.

**Comment by krstns** [comment]
I'm getting this error when I run the sample scene in the unity editor.
just made sure that the repo is clean but with the same result.

**Comment by khindemit** [comment]
I just tried the project in Unity 2020.3.41f1 on OSX switched to Android. It works fine for me.

https://user-images.githubusercontent.com/5675979/220310032-4950ef8d-428c-41d6-8147-db312a76bc85.mp4

Do you see the changes in your local git log from this commit?:
https://github.com/khindemit/unity-rlottie/commit/4f436141904ceef8d957d017aabb464ef07fec2a

**Comment by krstns** [comment]
yeah, I'm on that commit. I don't know how come it does not work on my side. on other projects, I have plenty of plugins which work just fine. I will try to spend some more time on it tonight. thanks for the support!

**Comment by krstns** [comment]
@khindemit I was unable to find the reason why it's not working on my end so I've asked a colleague of mine to try it on his mac. He cloned the repo and ended up with the same issue as mine.
Is it possible that when compiling the library you are 'installing' it somewhere system-wide which makes it available for your project? We have tried the standalone platform and android platform in the editor. Unity 2020.3.42f in his case.

**Comment by khindemit** [comment]
Hello @krstns, sorry for the late reply.
There are two libraries:
1. libLottiePlugin.dylib
2. librlottie.0.2.dylib
The first one depends on the second. But the second does not depend on any libraries. I'll ask a colleague of mine to try it out. Let's see if it works for him.

**Comment by khindemit** [comment]
Hey @krstns, can you please pull and try again. I compiled today the libraries for both arm64 and x86_64 abis. Maybe this will help to solve the issues you have. Please quit Unity when you pull, so that the libraries are loaded again when you open the project.

**Comment by krstns** [comment]
Here is a quick summary of what my test looks like and the outcome so you can check if I don't mess it up somewhere:
- unity is closed
- clone a repo again into a new directory
- open up the project in unity 2020.3.44 (pointing to `unity/RLottieUnity` directory) using the 'current platform' of the project
- at this stage I get these errors:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/942710/221741278-db03fcaf-4746-4477-a9e8-c952b1abf701.png">
- I open the SampleScene from `Assets/_Presentation/`
- I immediately get the following errors:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/942710/221741552-9d370664-7f10-4101-a447-1e4e458e8dce.png">
- I hit play and I get the result from the previous comment

**Comment by krstns** [comment]
@khindemit I did a different test.
I took a 'clean' MacBook, which never had any unity installed on it.
I've installed the latest 2020.3 release.
I've cloned the product.
Started the project and opened the scene - the same errors appeared immediately.

If it helps, I can arrange remote access to this computer.

**Comment by khindemit** [comment]
Hello @krstns, thanks a lot for checking it out! I don't have any ideas how to solve this issue. I can't unfortunately reproduce it on MacBook I have. Let's try to connect to your computer remotely, maybe we can find a solution.

**Comment by khindemit** [comment]
Hey @krstns I answered your email. Until now I don't have any response from you. Is everything ok? Can we do the debug session?

**Comment by khindemit** [comment]
Hello @krstns, I just pushed a new build of the native dynamic libraries for Mac OSX. Can you please check if the issue is fixed for you now?
The rlottie library has a version information in the CMake file. This makes symlink files to the rlottie library during the build. Previously I have not included the symlink files into the git control. That's why it was not working. For now as a workaround I removed the version information from the rlottie library build. In the future I will probably provide a version with the symlink files.

**Comment by krstns** [comment]
Hi @khindemit, thanks a lot for the quick response. I have tried it on my computer and it worked fine. I have also checked on the one you were working on and it looks good too!
Perfect!!
Thanks a lot for taking the time to solve it!
